# Lab | Handling Data Imbalance in Classification Models

For this lab and in the next lessons we will build a model on customer churn binary classification problem. You will be using files_for_lab/Customer-Churn.csv file.

## Scenario

You are working as an analyst with this internet service provider. You are provided with this historical data about your company's customers and their churn trends. Your task is to build a machine learning model that will help the company identify customers that are more likely to default/churn and thus prevent losses from such customers.

## Instructions

In this lab, we will first take a look at the degree of imbalance in the data and correct it using the techniques we learned on the class.

Here is the list of steps to be followed (building a simple model without balancing the data):

* Import the required libraries and modules that you would need.
* Read that data into Python and call the dataframe churnData.
* Check the datatypes of all the columns in the data. You would see that the column TotalCharges is object type. Convert this column into numeric type using pd.to_numeric function.
* Check for null values in the dataframe. Replace the null values.
* Use the following features: tenure, SeniorCitizen, MonthlyCharges and TotalCharges:
    * Scale the features either by using normalizer or a standard scaler.
    * Split the data into a training set and a test set.
    * Fit a logistic regression model on the training data.
    * Check the accuracy on the test data.
    
Note: So far we have not balanced the data.

Managing imbalance in the dataset

* Check for the imbalance.
* Use the resampling strategies used in class for upsampling and downsampling to create a balance between the two classes.
* Each time fit the model and see how the accuracy of the model is.

## Building a simple model without balancing the data

**Import the required libraries and modules that you would need.**

In [48]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

**Read that data into Python and call the dataframe churnData.**

In [49]:
churnData = pd.read_csv(r'C:\Users\Elena\Documents\IRONHACK\WEEK7\LABS\lab-handling-data-imbalance-classification\files_for_lab\Customer-Churn.csv')
churnData.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

  OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV  \
0             No          Yes               No          No          No   
1            Yes           No              Yes          No          No   
2            Yes          Yes               No          No          No   
3            Yes           No              Yes         Yes          No   
4             No           No               No          No          No   

  StreamingMovies        Contract  MonthlyCharges TotalCharges Churn  
0              No  Month-to-month           29.85        29.85    No  
1              No        One year           56.95       1889.5    No  
2              No  Month-to-month           53.85       108.15   Yes  
3              No        One year           42.30      1840.75    No  
4              No  Month-to-month           70.70       151.65   Yes

**Check the datatypes of all the columns in the data. You would see that the column TotalCharges is object type.
Convert this column into numeric type using pd.to_numeric function.**

In [50]:
churnData.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [51]:
# we see there is a space to fill otherwise i cannot convert the variable into numeric
churnData['TotalCharges'] = churnData['TotalCharges'].apply(lambda x: 0 if x == ' ' else x)

In [52]:
# convert the variable into a float
churnData["TotalCharges"] = pd.to_numeric(churnData["TotalCharges"], downcast="float")

In [53]:
churnData.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
MonthlyCharges      float64
TotalCharges        float32
Churn                object
dtype: object

**Check for null values in the dataframe. Replace the null values.**

In [54]:
churnData.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

Use the following features: tenure, SeniorCitizen, MonthlyCharges and TotalCharges:
* Scale the features either by using normalizer or a standard scaler.
* Split the data into a training set and a test set.
* Fit a logistic regression model on the training data.
* Check the accuracy on the test data.

In [55]:
churnData.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [56]:
y =churnData['Churn'] 
X= churnData.drop(['Churn'], axis=1)

In [57]:
X

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female              0     Yes         No       1           No   
1       Male              0      No         No      34          Yes   
2       Male              0      No         No       2          Yes   
3       Male              0      No         No      45           No   
4     Female              0      No         No       2          Yes   
...      ...            ...     ...        ...     ...          ...   
7038    Male              0     Yes        Yes      24          Yes   
7039  Female              0     Yes        Yes      72          Yes   
7040  Female              0     Yes        Yes      11           No   
7041    Male              1     Yes         No       4          Yes   
7042    Male              0      No         No      66          Yes   

     OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV  \
0                No          Yes               No          No          No   
1               Yes           No              Yes          No          No   
2               Yes          Yes               No          No          No   
3               Yes           No              Yes         Yes          No   
4                No           No               No          No          No   
...             ...          ...              ...         ...         ...   
7038            Yes           No              Yes         Yes         Yes   
7039             No          Yes              Yes          No         Yes   
7040            Yes           No               No          No          No   
7041             No           No               No          No          No   
7042            Yes           No              Yes         Yes         Yes   

     StreamingMovies        Contract  MonthlyCharges  TotalCharges  
0                 No  Month-to-month           29.85     29.850000  
1                 No        One year           56.95   1889.500000  
2                 No  Month-to-month           53.85    108.150002  
3                 No        One year           42.30   1840.750000  
4                 No  Month-to-month           70.70    151.649994  
...              ...             ...             ...           ...  
7038             Yes        One year           84.80   1990.500000  
7039             Yes        One year          103.20   7362.899902  
7040              No  Month-to-month           29.60    346.450012  
7041              No  Month-to-month           74.40    306.600006  
7042             Yes        Two year          105.65   6844.500000  

[7043 rows x 15 columns]

In [58]:
X=X[['tenure','SeniorCitizen','MonthlyCharges','TotalCharges']]

In [59]:
#Scale the features either by using normalizer or a standard scaler

In [62]:
from sklearn.preprocessing import MinMaxScaler

from sklearn.preprocessing import MinMaxScaler
# Normalizing data
transformer = MinMaxScaler().fit(X)
X_scaled = transformer.transform(X)
X = pd.DataFrame(X_scaled)
X.columns = ['tenure','SeniorCitizen','MonthlyCharges','TotalCharges']

In [63]:
X.head()

tenure  SeniorCitizen  MonthlyCharges  TotalCharges
0  0.013889            0.0        0.115423      0.003437
1  0.472222            0.0        0.385075      0.217564
2  0.027778            0.0        0.354229      0.012453
3  0.625000            0.0        0.239303      0.211951
4  0.027778            0.0        0.521891      0.017462

In [64]:
#Split the data into a training set and a test set.

In [65]:
# Splitting into train set and test set.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [66]:
#Fit a logistic regression model on the training data.

In [67]:
from sklearn.linear_model import LogisticRegression
classification = LogisticRegression(random_state=0, solver='lbfgs',
                  multi_class='ovr').fit(X_train, y_train)

predictions = classification.predict(X_test)

#D Check the accuracy on the test data.
print(classification.score(X_test, y_test))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))

0.8034066713981547
[[959  77]
 [200 173]]


## Managing imbalance in the dataset

In [68]:
#Checking for the imbalance

In [69]:
churnData["Churn"].value_counts()

No     5174
Yes    1869
Name: Churn, dtype: int64

In [70]:
#4 Managing imbalance in the dataset
#A Check for the imbalance.
imbalance_check = pd.DataFrame(y.value_counts())
print('imbalanced percentage:',round(imbalance_check['Churn'][0]/imbalance_check['Churn'].sum()*100,2),'%')

imbalanced percentage: 73.46 %


In [71]:
#We have imbalance data .We will fix it by undersampling and oversampling

In [72]:
from sklearn.utils import resample

category_0 = churnData[churnData['Churn'] == 'No']
category_1 = churnData[churnData['Churn'] == 'Yes']

**Downsampling**

In [73]:
category_0_undersampled = resample(category_0, 
                                   replace=False, 
                                   n_samples = len(category_1))

In [74]:
print(category_0_undersampled.shape)
print(category_1.shape)

(1869, 16)
(1869, 16)


In [75]:
data_downsampled = pd.concat([category_0_undersampled, category_1], axis=0)

In [76]:
data_downsampled['Churn'].value_counts()

Yes    1869
No     1869
Name: Churn, dtype: int64

In [77]:
X = data_downsampled.loc[:,['tenure','SeniorCitizen','MonthlyCharges']]
y = data_downsampled['Churn']

In [78]:
# Splitting into train set and test set.
#building the model with downsample data:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression
classification = LogisticRegression(random_state=0, solver='lbfgs',multi_class='ovr').fit(X_train, y_train)

predictions = classification.predict(X_test)

print(classification.score(X_test, y_test))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))

0.7580213903743316
[[291  88]
 [ 93 276]]


**Upsampling**

In [79]:
category_1_oversampled = resample(category_1, replace=True, n_samples = len(category_0))
print(category_0.shape)
print(category_1_oversampled.shape)
data_upsampled = pd.concat([category_0, category_1_oversampled], axis=0)
print(data_upsampled['Churn'].value_counts())

X = data_upsampled.loc[:,['tenure','SeniorCitizen','MonthlyCharges']]
y = data_upsampled['Churn']

(5174, 16)
(5174, 16)
No     5174
Yes    5174
Name: Churn, dtype: int64


In [80]:
#building the model with downsample data:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression
classification = LogisticRegression(random_state=0, solver='lbfgs',multi_class='ovr').fit(X_train, y_train)

predictions = classification.predict(X_test)

print(classification.score(X_test, y_test))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))

0.7246376811594203
[[762 282]
 [288 738]]
