## Lab | Customer Analysis Round 6

### Processing Data
(Further processing...)

One Hot/Label Encoding (categorical).

Concat DataFrames

### Linear Regression
Train-test split.
Apply linear regression.

### Model Validation
Description: R2,MSE,RMSE,MAE.

In [69]:
#Importing libraries
import pandas as pd
import numpy as np
import math
from sklearn import linear_model

In [70]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [71]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [72]:
#Getting the data 
df = pd.read_csv('marketing_customer_analysis.csv')
df.head()

Customer       State  Customer Lifetime Value Response  Coverage Education  \
0  BU79786  Washington              2763.519279       No     Basic  Bachelor   
1  QZ44356     Arizona              6979.535903       No  Extended  Bachelor   
2  AI49188      Nevada             12887.431650       No   Premium  Bachelor   
3  WW63253  California              7645.861827       No     Basic  Bachelor   
4  HB64268  Washington              2813.692575       No     Basic  Bachelor   

  Effective To Date EmploymentStatus Gender  Income  ...  \
0           2/24/11         Employed      F   56274  ...   
1           1/31/11       Unemployed      F       0  ...   
2           2/19/11         Employed      F   48767  ...   
3           1/20/11       Unemployed      M       0  ...   
4            2/3/11         Employed      M   43836  ...   

  Months Since Policy Inception Number of Open Complaints  Number of Policies  \
0                             5                         0                   1   
1                            42                         0                   8   
2                            38                         0                   2   
3                            65                         0                   7   
4                            44                         0                   1   

      Policy Type        Policy  Renew Offer Type  Sales Channel  \
0  Corporate Auto  Corporate L3            Offer1          Agent   
1   Personal Auto   Personal L3            Offer3          Agent   
2   Personal Auto   Personal L3            Offer1          Agent   
3  Corporate Auto  Corporate L2            Offer1    Call Center   
4   Personal Auto   Personal L1            Offer1          Agent   

  Total Claim Amount  Vehicle Class Vehicle Size  
0         384.811147   Two-Door Car      Medsize  
1        1131.464935  Four-Door Car      Medsize  
2         566.472247   Two-Door Car      Medsize  
3         529.881344            SUV      Medsize  
4         138.130879  Four-Door Car      Medsize  

[5 rows x 24 columns]

In [73]:
#Show the dataframe shape.
df.shape

(9134, 24)

In [74]:
df.columns

Index(['Customer', 'State', 'Customer Lifetime Value', 'Response', 'Coverage',
       'Education', 'Effective To Date', 'EmploymentStatus', 'Gender',
       'Income', 'Location Code', 'Marital Status', 'Monthly Premium Auto',
       'Months Since Last Claim', 'Months Since Policy Inception',
       'Number of Open Complaints', 'Number of Policies', 'Policy Type',
       'Policy', 'Renew Offer Type', 'Sales Channel', 'Total Claim Amount',
       'Vehicle Class', 'Vehicle Size'],
      dtype='object')

### PROCESSING DATA 

**Split x, y**

In [75]:
#y,X split.separate the features from the labels
y = df['Total Claim Amount']
X = df.drop(['Total Claim Amount'], axis=1)

In [76]:
#We will use the column total_claim_amount later as the target variable

**Normalizing the data**

In [77]:
#categorical features and numerical ones are going to be treated differently
X_num = X.select_dtypes(include = np.number)
X_cat = X.select_dtypes(include = np.object)
X_num.head()
X_cat.head()

Customer Lifetime Value  Income  Monthly Premium Auto  \
0              2763.519279   56274                    69   
1              6979.535903       0                    94   
2             12887.431650   48767                   108   
3              7645.861827       0                   106   
4              2813.692575   43836                    73   

   Months Since Last Claim  Months Since Policy Inception  \
0                       32                              5   
1                       13                             42   
2                       18                             38   
3                       18                             65   
4                       12                             44   

   Number of Open Complaints  Number of Policies  
0                          0                   1  
1                          0                   8  
2                          0                   2  
3                          0                   7  
4                          0                   1

Customer       State Response  Coverage Education Effective To Date  \
0  BU79786  Washington       No     Basic  Bachelor           2/24/11   
1  QZ44356     Arizona       No  Extended  Bachelor           1/31/11   
2  AI49188      Nevada       No   Premium  Bachelor           2/19/11   
3  WW63253  California       No     Basic  Bachelor           1/20/11   
4  HB64268  Washington       No     Basic  Bachelor            2/3/11   

  EmploymentStatus Gender Location Code Marital Status     Policy Type  \
0         Employed      F      Suburban        Married  Corporate Auto   
1       Unemployed      F      Suburban         Single   Personal Auto   
2         Employed      F      Suburban        Married   Personal Auto   
3       Unemployed      M      Suburban        Married  Corporate Auto   
4         Employed      M         Rural         Single   Personal Auto   

         Policy Renew Offer Type Sales Channel  Vehicle Class Vehicle Size  
0  Corporate L3           Offer1         Agent   Two-Door Car      Medsize  
1   Personal L3           Offer3         Agent  Four-Door Car      Medsize  
2   Personal L3           Offer1         Agent   Two-Door Car      Medsize  
3  Corporate L2           Offer1   Call Center            SUV      Medsize  
4   Personal L1           Offer1         Agent  Four-Door Car      Medsize

In [78]:
# Normalizing and Standardizing data - only for numerical variables

In [79]:
X_num.head()
X_num.shape

Customer Lifetime Value  Income  Monthly Premium Auto  \
0              2763.519279   56274                    69   
1              6979.535903       0                    94   
2             12887.431650   48767                   108   
3              7645.861827       0                   106   
4              2813.692575   43836                    73   

   Months Since Last Claim  Months Since Policy Inception  \
0                       32                              5   
1                       13                             42   
2                       18                             38   
3                       18                             65   
4                       12                             44   

   Number of Open Complaints  Number of Policies  
0                          0                   1  
1                          0                   8  
2                          0                   2  
3                          0                   7  
4                          0                   1

(9134, 7)

In [80]:
from sklearn.preprocessing import MinMaxScaler
MinMaxtransformer = MinMaxScaler().fit(X_num)
x_normalized = MinMaxtransformer.transform(X_num)
print(x_normalized.shape)

(9134, 7)


In [81]:
x_normalized = pd.DataFrame(x_normalized,columns=X_num.columns)
x_normalized.head()

Customer Lifetime Value    Income  Monthly Premium Auto  \
0                 0.010629  0.562847              0.033755   
1                 0.062406  0.000000              0.139241   
2                 0.134960  0.487763              0.198312   
3                 0.070589  0.000000              0.189873   
4                 0.011245  0.438443              0.050633   

   Months Since Last Claim  Months Since Policy Inception  \
0                 0.914286                       0.050505   
1                 0.371429                       0.424242   
2                 0.514286                       0.383838   
3                 0.514286                       0.656566   
4                 0.342857                       0.444444   

   Number of Open Complaints  Number of Policies  
0                        0.0               0.000  
1                        0.0               0.875  
2                        0.0               0.125  
3                        0.0               0.750  
4                        0.0               0.000

**One Hot Encoding**

In [82]:
#One hot encoder
X_cat.head()
X_cat.shape

Customer       State Response  Coverage Education Effective To Date  \
0  BU79786  Washington       No     Basic  Bachelor           2/24/11   
1  QZ44356     Arizona       No  Extended  Bachelor           1/31/11   
2  AI49188      Nevada       No   Premium  Bachelor           2/19/11   
3  WW63253  California       No     Basic  Bachelor           1/20/11   
4  HB64268  Washington       No     Basic  Bachelor            2/3/11   

  EmploymentStatus Gender Location Code Marital Status     Policy Type  \
0         Employed      F      Suburban        Married  Corporate Auto   
1       Unemployed      F      Suburban         Single   Personal Auto   
2         Employed      F      Suburban        Married   Personal Auto   
3       Unemployed      M      Suburban        Married  Corporate Auto   
4         Employed      M         Rural         Single   Personal Auto   

         Policy Renew Offer Type Sales Channel  Vehicle Class Vehicle Size  
0  Corporate L3           Offer1         Agent   Two-Door Car      Medsize  
1   Personal L3           Offer3         Agent  Four-Door Car      Medsize  
2   Personal L3           Offer1         Agent   Two-Door Car      Medsize  
3  Corporate L2           Offer1   Call Center            SUV      Medsize  
4   Personal L1           Offer1         Agent  Four-Door Car      Medsize

(9134, 16)

In [83]:
# We have 15 categorical variables. Do we do with all of them? Or just select some? 
#In this case we chose only one variable(Coverage)

In [84]:
X_cat.columns

Index(['Customer', 'State', 'Response', 'Coverage', 'Education',
       'Effective To Date', 'EmploymentStatus', 'Gender', 'Location Code',
       'Marital Status', 'Policy Type', 'Policy', 'Renew Offer Type',
       'Sales Channel', 'Vehicle Class', 'Vehicle Size'],
      dtype='object')

In [85]:
X_cat_reduced= X_cat[['Coverage']] # Note:one braquet for creting an array. Doble braquet for creating a df.
X_cat.head()
X_cat_reduced.head()

Customer       State Response  Coverage Education Effective To Date  \
0  BU79786  Washington       No     Basic  Bachelor           2/24/11   
1  QZ44356     Arizona       No  Extended  Bachelor           1/31/11   
2  AI49188      Nevada       No   Premium  Bachelor           2/19/11   
3  WW63253  California       No     Basic  Bachelor           1/20/11   
4  HB64268  Washington       No     Basic  Bachelor            2/3/11   

  EmploymentStatus Gender Location Code Marital Status     Policy Type  \
0         Employed      F      Suburban        Married  Corporate Auto   
1       Unemployed      F      Suburban         Single   Personal Auto   
2         Employed      F      Suburban        Married   Personal Auto   
3       Unemployed      M      Suburban        Married  Corporate Auto   
4         Employed      M         Rural         Single   Personal Auto   

         Policy Renew Offer Type Sales Channel  Vehicle Class Vehicle Size  
0  Corporate L3           Offer1         Agent   Two-Door Car      Medsize  
1   Personal L3           Offer3         Agent  Four-Door Car      Medsize  
2   Personal L3           Offer1         Agent   Two-Door Car      Medsize  
3  Corporate L2           Offer1   Call Center            SUV      Medsize  
4   Personal L1           Offer1         Agent  Four-Door Car      Medsize

Coverage
0     Basic
1  Extended
2   Premium
3     Basic
4     Basic

In [86]:
#one hot encoding is a way to turn categorical variables into multiple numerical columns
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder().fit(X_cat_reduced)
print(encoder.categories_)
encoded = encoder.transform(X_cat_reduced).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)
onehot_encoded.head()

[array(['Basic', 'Extended', 'Premium'], dtype=object)]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


Basic Extended Premium
0   1.0      0.0     0.0
1   0.0      1.0     0.0
2   0.0      0.0     1.0
3   1.0      0.0     0.0
4   1.0      0.0     0.0

In [87]:
#because one of the variables can be deduced from the others, there is no point in keeping all these columns around.
#We drop one of them
onehot_encoded = onehot_encoded.drop(['Basic'],axis=1)
onehot_encoded.head()

Extended Premium
0      0.0     0.0
1      1.0     0.0
2      0.0     1.0
3      0.0     0.0
4      0.0     0.0

### Concatenate data frames

In [88]:
# let's merge all this information together into a single dataset with all features, now numerical
X = pd.concat([x_normalized, onehot_encoded], axis=1)
X.head()
# X = pd.concat([X_num, onehot_encoded],axis=1)
# X.head(2)

Customer Lifetime Value    Income  Monthly Premium Auto  \
0                 0.010629  0.562847              0.033755   
1                 0.062406  0.000000              0.139241   
2                 0.134960  0.487763              0.198312   
3                 0.070589  0.000000              0.189873   
4                 0.011245  0.438443              0.050633   

   Months Since Last Claim  Months Since Policy Inception  \
0                 0.914286                       0.050505   
1                 0.371429                       0.424242   
2                 0.514286                       0.383838   
3                 0.514286                       0.656566   
4                 0.342857                       0.444444   

   Number of Open Complaints  Number of Policies  (Extended,)  (Premium,)  
0                        0.0               0.000          0.0         0.0  
1                        0.0               0.875          1.0         0.0  
2                        0.0               0.125          0.0         1.0  
3                        0.0               0.750          0.0         0.0  
4                        0.0               0.000          0.0         0.0

In [89]:
X.rename(columns={('Extended',): 'Extended Coverage', ('Premium',):'Premium Coverage'}, inplace=True)
X.head(2)

Customer Lifetime Value    Income  Monthly Premium Auto  \
0                 0.010629  0.562847              0.033755   
1                 0.062406  0.000000              0.139241   

   Months Since Last Claim  Months Since Policy Inception  \
0                 0.914286                       0.050505   
1                 0.371429                       0.424242   

   Number of Open Complaints  Number of Policies  Extended Coverage  \
0                        0.0               0.000                0.0   
1                        0.0               0.875                1.0   

   Premium Coverage  
0               0.0  
1               0.0

### Linear Regression
Apply linear regression model to our processed data.

In [90]:
y = df[['Total Claim Amount']]
y.head()

Total Claim Amount
0          384.811147
1         1131.464935
2          566.472247
3          529.881344
4          138.130879

In [91]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1000)

In [92]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(6850, 9)
(2284, 9)
(6850, 1)
(2284, 1)


In [93]:
X_train.head()
X_test.head()

Customer Lifetime Value    Income  Monthly Premium Auto  \
5114                 0.181775  0.814155              0.181435   
2438                 0.007893  0.425651              0.016878   
312                  0.048892  0.858733              0.050633   
4039                 0.093805  0.624329              0.080169   
5801                 0.007938  0.410668              0.012658   

      Months Since Last Claim  Months Since Policy Inception  \
5114                 0.171429                       0.191919   
2438                 0.114286                       0.353535   
312                  0.085714                       0.191919   
4039                 0.628571                       0.505051   
5801                 0.171429                       0.121212   

      Number of Open Complaints  Number of Policies  Extended Coverage  \
5114                        0.0               0.125                0.0   
2438                        0.0               0.000                0.0   
312                         0.0               0.625                0.0   
4039                        0.4               0.125                1.0   
5801                        0.0               0.000                0.0   

      Premium Coverage  
5114               1.0  
2438               0.0  
312                0.0  
4039               0.0  
5801               0.0

Customer Lifetime Value    Income  Monthly Premium Auto  \
768                  0.006673  0.000000              0.016878   
1477                 0.032330  0.346466              0.236287   
3902                 0.081089  0.791680              0.189873   
2713                 0.208231  0.000000              0.472574   
165                  0.072127  0.218802              0.029536   

      Months Since Last Claim  Months Since Policy Inception  \
768                  0.200000                       0.282828   
1477                 0.657143                       0.545455   
3902                 0.342857                       0.050505   
2713                 0.685714                       0.212121   
165                  0.342857                       0.282828   

      Number of Open Complaints  Number of Policies  Extended Coverage  \
768                         0.0               0.000                0.0   
1477                        0.4               0.000                0.0   
3902                        0.0               0.750                0.0   
2713                        0.0               0.125                0.0   
165                         0.0               0.125                0.0   

      Premium Coverage  
768                0.0  
1477               0.0  
3902               0.0  
2713               1.0  
165                0.0

In [94]:
y_test.head()

Total Claim Amount
768           312.000000
1477          466.318191
3902          508.800000
2713         1245.600000
165           465.414770

In [95]:
#we train/fit our model with our training set.
lm = linear_model.LinearRegression()
model = lm.fit(X_train,y_train)

In [96]:
# But now we evaluate it in the TEST portion of the data, that we did not use for training.
# This way we know our model is genuinely guessing our donations, not just repeating the values it has seen in the training data
from sklearn.metrics import r2_score
predictions = lm.predict(X_test)
predictions

array([[418.62496069],
       [570.34924031],
       [378.59537629],
       ...,
       [532.84922561],
       [539.28596278],
       [370.37923074]])

In [97]:
r2_score(y_test, predictions)

0.5156100687380555

### Model Validation
R2/.
MSE/
RMSE/
MAE/

In [98]:
from sklearn.metrics import mean_squared_error, r2_score

In [99]:
mse = mean_squared_error(y_test, predictions)
print(mse)

41029.5108695524


In [100]:
#we calculate the rmse to have a comparable measure with our data
rmse = math.sqrt(mse)
print(rmse)

202.5574261031977


In [101]:
r2 = r2_score(y_test, predictions)
r2


0.5156100687380555